name: First

on: push

jobs:

  job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
    
      - name: Display env in sorted order
        run: env | sort
        
  job2:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
    
      - name: Display env in sorted order
        run: "Get-ChildItem Env: | Sort-Object Name"
