name: first
on: push
jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
    - name: Step One
      uses: actions/checkout@v3
      run: env | sort
  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
    - name: Step two
      uses: actions/checkout@v3
      run: "Get-ChildItem Env: | Sort-Object Name"
